booklib/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booklibrary.urls')),
]

booklibrary/urls.py
from django.contrib import admin
from .views import BookDetail,BookList,BookListdemo,Usersview,Friendview
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns




app_name='booklibrary'
urlpatterns = [
    path('post/byuser/<int:user_id>', views.postbyuser, name='postbyuser'),
    path('book/<int:pk>', BookDetail.as_view(), name='book_paste_detail'),
    path('uploadbook/', views.add_post, name='create'),
    path('register/', views.signup_view,name='register'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view,name='logout'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friends,name='change_friends'),
    # url(r'^(?P<slug>[-\w]+)/comment/$',Comment.as_view(),name='bookcomment'),
   #path('addcomment/<int:id>', Comment.as_view(), name='addcomment'),
    path('comment/<int:post_id>', views.display_comment, name='bookcomment'),
    path('addcomment/<int:id>', views.add_comment, name='addcomment'),
    #path('addcomment/<int:post_id>',views.add_comment,name='add_comment'),
    path('category/<int:category_id>', views.display_category, name='displaycategory'),

    path('profile/', views.profile,name='userprofile'),
    url(r'^profile(?P<pk>\d+)/$',views.otherprofile,name='otherusersprofile'),
    
    path('editprofile/', views.edit_profile,name='edituserprofile'),
    #path('userupdateform/', views.userupdateform,name='userupdateform'),
    path('', BookList.as_view(), name='book_paste_list'),
    path('books/show', BookListdemo.as_view(), name='book_paste_listdemo'),
   # path('createinfouser/', createinfouser.as_view(), name='createinfouser'),
    path('otherusers/', Usersview.as_view(), name='otherusers'),
    path('friendview/', Friendview.as_view(), name='friendview'),
    path('like/',views.like_post,name='like_post'),
    path('favourites/<int:id>', views.favourite_book,name='favourite_book'),
    path('favouritebooks/', views.userfavourite_book,name='userfavourite_book'),


   
    #path('book/delete/<int:pk>', BookDelete.as_view(), name='book_paste_delete'),
   # path('userprofileupdate/<int:pk>',  userprofileUpdate.as_view(), name=' userprofileupdate'),
    
   
    #path('books/category/(?P<pk>[\d]+)/$', Bookcategory.as_view(), name='post_by_category' )
    #url(r'^category/(?P<category_slug>[-\w]+)/$',views.list_of_post_by_category,name='post_by_category')




]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

booklibrary/forms.py
from django import forms
from .models import Post,Comment,UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm



class PostForm(forms.ModelForm):

	        title = forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	        '''
	        slug = forms.SlugField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))

	        	'''
	        text =  forms.CharField(widget=forms.Textarea(
	        	attrs={
	        			'class':'form-control',


	        	}))
	        author =  forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	        class Meta:
	        	model = Post
	        	exclude = ['created_on','user','favourite','likes']

class CommentForm(forms.ModelForm):
	
	text =  forms.CharField(widget=forms.Textarea(
	        	attrs={
	        			'class':'form-control',


	        	}))
	class Meta: 
 		model = Comment 
 		fields = ['text']

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True,widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
			) 
	def save(self,commit = True):
		user = super(RegistrationForm,self).save(commit = False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()
class EditProfileForm(forms.ModelForm):
	 email = forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	   
	 first_name = forms.SlugField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	        
	 last_name =  forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	 class Meta:
	 	model = User
	 	fields = [
					'email',
					'first_name',
					'last_name',
					
					'password'
					]
class UserUpdateForm(forms.ModelForm):
	description =  forms.CharField(widget=forms.Textarea(
	        	attrs={
	        			'class':'form-control',


	        	}))
	city =  forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	age =  forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	website =  forms.CharField(widget=forms.TextInput(
	        	attrs={
	        			'class':'form-control',


	        	}))
	


	        	

	class Meta:
		model = UserProfile
		fields = [
			'description',
			'gender',
			'age',
			'city',
			'website',
			'image'
	]
				

booklibrary/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic.edit import CreateView,UpdateView
from .models import Post,Category,Comment,UserProfile,Friend
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView 
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from .forms import PostForm,CommentForm
from django.contrib.auth.models import User
from .forms import RegistrationForm,EditProfileForm, UserUpdateForm
from django.contrib.auth.forms import UserChangeForm
from django.views.generic import TemplateView
from django.db.models import Q
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponseRedirect
import requests


# Create your views here.
'''
@login_required(login_url="login/")
def add_post(request):
 form = PostForm(request.POST or None)
 if form.is_valid():
  	post = form.save() 
  	return redirect('booklibrary:book_paste_list') 
 return render(request, 'booklibrary/post_form.html',{ 'form': form })
''' 
def index(request):
	r = requests.get('http://httpbin.org/status/418')
	print(r.text)
	return HttpResponse('<pre>' + r.text + '</pre>')





@login_required(login_url="/login/")
def	add_post(request):
	if request.method =='POST':
		a_form = PostForm(request.POST,request.FILES)
		if a_form.is_valid:
			#save to db
			post= a_form.save(commit=False)
			post.user = request.user
			post.save()
			return redirect('booklibrary:book_paste_list')
	else:
		a_form =  PostForm()		
		return render(request, 'booklibrary/post_form.html',{ 'a_form': a_form })


#@login_required(login_url="login/")
'''
def view_comment(request, slug):
 		post = get_object_or_404(Post,slug=slug)
 		if request.method == 'POST':
 			form = 	CommentForm(request.POST)
 			if form.is_valid():
 				comment = form.save(commit=False)
 				comment.post = post
 				comment.save()
 				return redirect('booklibrary:bookcomment', slug=post.slug)
 		else:
 				form = CommentForm()
 				return render(request, 'booklibrary/bookcomment.html',{ 'form': form })
		
'''
# class Comment(ListView):
# 	model= Comment
# 	template_name = 'booklibrary/bookcomment.html'
# 	queryset =  Comment.objects.filter('post_id')
# 	context_object_name = 'queryset'

def display_comment(request, post_id):
	text = Comment.objects.filter(post_id= post_id).order_by('-created_on')
	
			
	context =    {'text':text}
	return render(request, 'booklibrary/bookcomment.html', context)



@login_required(login_url="/login/")
def add_comment(request,id):
	post = get_object_or_404(Post,id=id)
	
	if request.method == 'POST':
			p_form = CommentForm(request.POST)
			if p_form.is_valid()  :
				comment=p_form.save(commit=False)
				comment.post = post
				comment.name = request.user
				comment.save()
				
				#return redirect(request.path) 
				return redirect('booklibrary:book_paste_detail',pk=id)
	else:
			p_form = CommentForm()
			context = {'p_form':p_form}
			return render(request, 'booklibrary/addcomment.html', context)



		
'''
		if request.method == 'POST':
			form = 	CommentForm(request.POST)
			if form.is_valid():
				comment = form.save(commit=False)
				comment.post = post
				comment.save()
				return redirect('booklibrary:bookcomment')

		else: CommentForm
			form = CommentForm()
			'''
		
		#post = get_object_or_404(Post)

		
		# post = get_object_or_404(Post)
		# if request.method == 'POST':
		# 	form = 	CommentForm(request.POST)
		# 	if form.is_valid():
		# 		comment = form.save(commit=False)
		# 		comment.post = post
		# 		comment.save()
		# 		return redirect('booklibrary:bookcomment')

		# else:
		# 	form = CommentForm()
		# 	return render(request,'booklibrary/bookcomment.html', context, {'form':form})

def display_category(request,category_id):
	text = Post.objects.filter(category_id=category_id)
	
	query = request.GET.get('q')
	if query:
		text = text.filter(Q(title__icontains=query)|
						   Q(text__icontains=query)|
						   Q(author__icontains=query)
						   
						   )

		
	paginator = Paginator(text,24)		
	page = request.GET.get('page')
	text = paginator.get_page(page)
	try:
		text = paginator.page(page)
	except PageNotAnInteger:
			text = paginator.page(1)
	except EmptyPage:
			text = paginator.page(paginator.num_page)
 


	context = {'text': text}
	return render(request, 'booklibrary/displaycategory.html', context)

def postbyuser(request,user_id):
	user =	 Post.objects.filter(user_id=user_id)

	paginator = Paginator(user,24)		
	page = request.GET.get('page')
	user = paginator.get_page(page)
	try:
		user = paginator.page(page)
	except PageNotAnInteger:
			user = paginator.page(1)
	except EmptyPage:
			user = paginator.page(paginator.num_page)
	context = {'user': user}
	return render(request, 'booklibrary/userprofile_form.html', context)
	











def like_post(request):
	obj = get_object_or_404(Post,id=request.POST.get('obj_id'))
	is_liked = False
	if obj.likes.filter(id=request.user.id).exists():
		obj.likes.remove(request.user)
		is_liked = False
	else:	
			obj.likes.add(request.user)
			is_liked = True
	return HttpResponseRedirect(obj.get_absolute_url())


'''
class createinfouser(CreateView):
	model = UserProfile
	fields =  ['description','city','website','image']
	'''


'''
class Bookcomment(DetailView):
   model = Comment
   template_name = 'booklibrary/bookcomment.html'	
   queryset = Comment.objects.all() 
   context_object_name = 'queryset'
   
class Comment(CreateView):
	 model = Comment

	 fields = ['name','text']

'''

class BookList(ListView):
	
	 template_name = 'booklibrary/booklist.html'
	 def get(self,request):
	  	 model = Post
	  	 queryset = Post.objects.all().order_by('-created_on')
	  	 query = request.GET.get("q")
	  	 if query:
	  	 	queryset =  queryset.filter(
	  	 			Q(title__icontains=query)|
					Q(text__icontains=query)|
					Q(author__icontains=query)
	  	 			
	  	 									)

	  	 									



	  	 paginator = Paginator( queryset,24)
	  	 page = request.GET.get('page')
	  	 queryset = paginator.get_page(page)
	  	 try:
	  	 	 queryset = paginator.page(page)
	  	 except PageNotAnInteger:
	  	 	 queryset = paginator.page(1)
	  	 except EmptyPage:
	  	 	 queryset = paginator.page(paginator.num_page)
 



	  	 args = {'queryset':queryset }
	  	 return render(request,self.template_name,args)




class BookDetail(DetailView):
	
	template_name = 'booklibrary/bookdetail.html'
	def get(self,request,pk):
		text = Comment.objects.filter(post_id= pk).order_by('-created_on')
		model = Post
		obj = Post.objects.get(pk=pk)
		is_liked = False
		is_favourite =False
		if obj.likes.filter(id=request.user.id).exists():
			is_liked =True
		if obj.favourite.filter(id=request.user.id).exists():
			is_favourite =True

	
			
		context =    {'text':text,'obj':obj,'is_liked':is_liked,'total_likes':obj.total_likes(),'is_favourite':is_favourite}
		return render(request, self.template_name, context)


def userfavourite_book(request):
	user = request.user
	favourite_posts = user.favourite.all()
	
	query = request.GET.get('q')
	if query:
	  	 	favourite_posts =favourite_posts.filter(Q(title__icontains=query)|
						   Q(text__icontains=query)|
						   Q(author__icontains=query)
						  
						   )
	paginator = Paginator( favourite_posts,24)
	page = request.GET.get('page')
	favourite_posts = paginator.get_page(page)
	try:
	  	 	 favourite_posts = paginator.page(page)
	except PageNotAnInteger:
	  	 	 favourite_posts = paginator.page(1)
	except EmptyPage:
		favourite_posts = paginator.page(paginator.num_page)
 
	context ={'favourite_posts':favourite_posts}
	return render(request,'booklibrary/userfavourite_book.html',context)



def favourite_book(request,id):
	obj = get_object_or_404(Post,id=id)
	if obj.favourite.filter(id=request.user.id).exists():
		obj.favourite.remove(request.user)
	else:
			obj.favourite.add(request.user)
	return HttpResponseRedirect(obj.get_absolute_url())			



class BookListdemo(ListView):
	 model = Category
	 template_name = 'booklibrary/booklistdemo.html'
	 queryset = Category.objects.all()
	 context_object_name = 'queryset'


#
#@login_required(login_url="/login/")
class Usersview(TemplateView):
	 template_name = 'booklibrary/community.html'
	 def get(self,request):

		 users = User.objects.exclude(id=request.user.id).order_by('?')
		 #friend = Friend.objects.get(current_user=request.user)
		 #friends = Friend.objects.all()
		 #ends = Friend.objects.all()
		 query = request.GET.get('q')
		 if query:
		 	#friends  = friends .filter(username__icontains=query)
		 	users = users .filter(username__icontains=query)
								   
		 args = {'users':users }
		 return render(request,self.template_name,args)



class Friendview(TemplateView):
	 template_name = 'booklibrary/notification.html'
	 def get(self,request):

		
		 
		 friend = Friend.objects.get(current_user=request.user)
		 friends = friend.users.all().order_by('username')
		 #ends = Friend.objects.all()
		 query = request.GET.get('q')
		 if query:
		 	friends  = friends .filter(username__icontains=query)
		 	
								   
		 args = {'friends':friends}
		 return render(request,self.template_name,args)


#class BookDelete(DeleteView):
	#model = Post
	#success_url = reverse_lazy('booklibrary:book_paste_edit')

def signup_view(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			 form.save()
			 

			 return redirect('booklibrary:login')
	else:
		form = RegistrationForm()
		
	return render(request,'booklibrary/signup.html',{'form':form})

def login_view(request):
	if request.method =='POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#Log user in
			user = form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else:	

booklibrary/templates/booklibrary/bookdetail.html
 
{% load static from staticfiles %} 




<!doctype html>
<html>
		<head>
											<meta charset="utf-8">
											<link type="text/css" rel="stylesheet" href="{% static 'booklibrary/detail.css' %}">
											
											<meta name="viewport" content="width=device-width, initial-scale=1">
											<title></title>
											<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
											<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
					  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
					  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

									<link  type="text/css"  rel="stylesheet" href="{% static 'booklibrary/bootstrap.min.css' %}">
									
									<script>
					
											function addone(field) {
						field.value = Number(field.value) + 1;
						}

						function subtractone(field) {
						field.value = Number(field.value) - 1;
						}
		</script>
		</head>
				<body>

		<header>
		<div class='head'>
			<h1><img src="{% static 'booklibrary/kkk.jpg' %}"  class="logo" /></h1>
		<div class="search-box">
				
			
			<hr/>	
</div>
</div>
		</header>
		<ul class="topnav">
			  <li><a class="active" href="{% url 'booklibrary:book_paste_list' %}">Home</a></li>
			  <li><a href="{% url 'booklibrary:book_paste_listdemo'  %}">Categories</a></li>
			  <li><a href="{% url 'booklibrary:create'  %}">Upload a book</a></li>
			  {% if not request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:login'  %}">Login</a></li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:otherusers'  %}">Community</a></li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:userfavourite_book'  %}">Favourite books</a></li>
			  {% endif %}
			  <li class="right"><a href="{% url 'booklibrary:userprofile'  %}">Profile</a></li>
		</ul>
		
			<div class='content'>
			<div class='container'>
		
				<div class='media'>
					<div class='media-left'>
						<img src="{{ obj.book_cover.url}}" width='180px' height='250px' class='media-object pic'/>
					</div>
					<div class='media-body'>
						<h1 class='media-heading'>{{obj.title}}</h1>
						<h3>written by {{ obj.author }}</h3>
						<h4>in {{ obj.category }}</h4>
						<p>uploaded by {{ obj.user }}</p>
						<p>created on {{ obj.created_on }}</p>
						<a href="{{ obj.upload_book.url }}"><h4><button type='button' class='btn btn-success'>
								<span style=" color:white" >Read book</span>
						</button></h4></a>
						<a href="{{ obj.upload_book.url }}" download><p><button type='button' class='btn btn-warning'>
						Download book
						</button></p></a>
						
					
					</div>
					
					<h4 >
					{{ obj.text }}	

					</h4>

					{{ total_likes }} Like{{ total_likes|pluralize }} 
					{% if request.user.is_authenticated %}
					<form method='POST' action='{% url "booklibrary:like_post" %}' >
						{% csrf_token %}
				
					<!--input type="submit" onclick="this.disabled = true" value="Save" -->
					
					{% if is_liked %}
							<button type='submit' name='obj_id' class='btn btn-danger' value='{{ obj.id }}'>Unlike</button>
					{% else %}
							<button type='submit' name='obj_id' class='btn btn-primary' value='{{ obj.id }}'>like</button>
					{% endif %}



						
						 <a href="{% url 'booklibrary:addcomment' obj.id  %}">&#128172 leave a comment</a> 
					{% if is_favourite %}	 
					<a href='{% url "booklibrary:favourite_book" id=obj.id %}'>
						<i class="fas fa-heart lg">Save
							
						</i>
					</a>
					{% else %}
							<a href='{% url "booklibrary:favourite_book" id=obj.id %}'>
						<i class="far fa-heart lg">Save
							
						</i>
					</a>
					{% endif %}

				</form>
				{% else %}
				 <p> please login to like or leave a comment</p>
				{% endif %}


					{% if text %}
							<h3>Comments</h3>
							<p>total number of comments {{ text.count }}</p>


					 {% for comment in text %}
							
				<div class='media'>
						
						<div class='media-left'>
							{% if user.userprofile.image %}
							<img src="{{ user.userprofile.image.url}}"  class='media-object img-rounded img-responsive pic1'/>
							{% endif %}
						</div>
						<div class='media-body'>
							<h3><b> {{ comment.name }} </b> <small>said {{ comment.text }}</small></h3>
							 <p>said on {{ comment.created_on }}</p>
						</div>
						
						
					
				</div>
				<hr />
					{% endfor %}
					{% else %}
							<h3>No Comments</h3>
					{% endif %}		
</div> 
</form>
					
					
					
				
					
				</div>
				
			</div>
			

	</body>
</html>	

booklibrary/templates/booklibrary/booklistdemo.html
{% load static from staticfiles %}
<!doctype html>
<html>
		<head>
											<meta charset="utf-8">
											<link type="text/css" rel="stylesheet" href="{% static 'booklibrary/category.css' %}">
											
											<meta name="viewport" content="width=device-width, initial-scale=1">
											<title></title>
											<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
					  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
					  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

									<link  type="text/css"  rel="stylesheet" href="{% static 'booklibrary/bootstrap.min.css' %}">
		</head>
		<body>
		<header>
		<div class='head'>
		<h1><img src="{% static 'booklibrary/kkk.jpg' %}"  height='50px' width='220px'/></h1>
		<div class="search-box">
				
			<hr/>	
</div>
</div>
		</header>
		<ul class="topnav">
			  <li><a href="{% url 'booklibrary:book_paste_list' %}">Home</a></li>
			  <li><a  class="active" href="{% url 'booklibrary:book_paste_listdemo'  %}">Categories</a></li>
			  <li><a href="{% url 'booklibrary:create'  %}">Upload a book</a></li>
			  {% if not request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:login'  %}">Login</a></li>
			  {% endif %}
			 {% if request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:otherusers'  %}">Community</a></li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:userfavourite_book'  %}">Favourite books</a></li>
			  {% endif %}
			  <li class="right"><a href="{% url 'booklibrary:userprofile'  %}">Profile</a></li>
		</ul>
			<div class='welcome'>
						<h3>Categories</h3>
					</div>
		<div class='container'>
			{% if queryset %}
			<div class='row '>
			
				{% for categories in queryset %}
				<div class='col-sm-2'>
					<div class="grey">
					<button type='button' class='btn btn-default'>
									<h3><a href="{% url 'booklibrary:displaycategory' categories.id %}">{{categories.name}}</a></h3>
					</button>
				</div>
						
				</div>
				 {% endfor %}
			</div>
			{% else %}
  	<h1>No recent books</h1>
 {% endif %}			
		</div>
		
		
		</body>
	</html>	

booklibrary/templates/booklibrary/community.html
{% load static from staticfiles %}






<!doctype html>
<html>
		<head>
											<meta charset="utf-8">
											<link type="text/css" rel="stylesheet" href="{% static 'booklibrary/community.css' %}">
											
											<meta name="viewport" content="width=device-width, initial-scale=1">
											<title></title>
											<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
					  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
					  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

									<link  type="text/css"  rel="stylesheet" href="{% static 'booklibrary/bootstrap.min.css' %}">
		</head>
		<body>
		<header>
		<div class='head'>
		<h1><img src="{% static 'booklibrary/kkk.jpg' %}"  class='logo'/></h1>
		<div class="search-box">
				<form method ='GET' action=''>
					<p><input type="text" class="search-text" placeholder="search..." name="q" value='{{ request.get.q }}' > 
				<input type="submit" value="search" class='searchbtn'></p>
			</form>
			<hr/>	
</div>
</div>
		</header>
		<ul class="topnav">
			 <li><a  href="{% url 'booklibrary:book_paste_list' %}">Home</a></li>
			  <li><a href="{% url 'booklibrary:book_paste_listdemo'  %}">Categories</a></li>
			  <li><a href="{% url 'booklibrary:create'  %}">Upload a book</a></li>
			  <li><a class="active" href="{% url 'booklibrary:otherusers'  %}">Community</a></li>
			  {% if request.user.is_authenticated %}
			  <li><a href="{% url 'booklibrary:userfavourite_book'  %}">Favourite books</a></li>
			  {% endif %}
			  <li class="right"><a href="{% url 'booklibrary:userprofile'  %}">Profile</a></li>
		</ul>
			<div class='welcome'>
						<h3>Community
						<a href="{% url 'booklibrary:friendview'  %}"><button type='button' class='btn btn-warning fol'>
								view friends
							</button></a></h3>
			</div>

		<div class='content'>	
		<div class='container-fluid'>
			
				
				<div class='tex'>
						<h3>People You May Know</h3>
				</div>		
						{% for user in users %}
							{% if not user in friends %}
					
							{% if user.userprofile.image %}
							<img src="{{ user.userprofile.image.url}}" class='media-object img-rounded pic'/>
							{% endif %}
						
							<h1 class='media-heading'>{{ user.username }}</h1>
							<h3>{{ user.userprofile.description }}</h3>
							
							<h4><button type='button' class='btn btn-success'>
									<a href="{% url 'booklibrary:otherusersprofile' pk=user.pk  %}"><span style=" color:white" >View Profile</span></a></h4>
							</button>
							<h4><a href="{% url 'booklibrary:change_friends' operation='add' pk=user.pk %}"><button type='button' class='btn btn-warning fol'>
								Follow
							</button></a></h4>
						
					<hr />
					
				
				{% endif %}

				{% endfor %}
				
					
					
				
						
							
						
							
									
				
					
				
		</div>
		
		
		
		
		
		
		</div>
		
		</body>
	</html>	

booklibrary/templates/booklibrary/post_confirm_delete.html
<h1>Really delete  {{ object.title }}?</h1>
 <h2>This action cannot be undone</h2> 
 <form action="{% url 'booklibrary:book_paste_delete' object.id %}" method="POST"> 
 	{% csrf_token %} 
 	<input type="submit" value="Delete"> </form>